# Generated by Django 5.2.17 on 2026-09-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
    ]
