# Generated by Django 5.2.17 on 2026-09-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('exploring', 'Currently Exploring'), ('fun', 'For Fun')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
